import React, { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

type Language = 'th' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  th: {
    home: 'หน้าแรก',
    news: 'ข่าวสาร',
    trade: 'ซื้อ-ขาย',
    history: 'ประวัติ',
    wallet: 'กระเป๋าเงิน',
    settings: 'ตั้งค่า',
    gold: 'ทองคำ',
    latestPrice: 'ราคาล่าสุด',
    change24h: '24ชม.',
    buy: 'ซื้อ',
    sell: 'ขาย',
    deposit: 'ฝากเงิน',
    staking: 'Staking',
    withdraw: 'ถอนเงิน',
    myStaking: 'My Staking',
    recentTransactions: 'รายการล่าสุด',
    totalBalance: 'ยอดเงินทั้งหมด',
    verification: 'ยืนยันตัวตน',
    bankDetails: 'Bank Details',
    changePassword: 'เปลี่ยนรหัสผ่าน',
    login: 'เข้าสู่ระบบ',
    register: 'สมัครสมาชิก',
    username: 'ชื่อผู้ใช้',
    password: 'รหัสผ่าน',
    email: 'อีเมล',
    phone: 'เบอร์มือถือ',
    confirmPassword: 'ยืนยันรหัสผ่าน',
    save: 'บันทึก',
    firstName: 'ชื่อ',
    lastName: 'นามสกุล',
    address: 'ที่อยู่',
    network: 'เครือข่าย',
    accountName: 'ชื่อบัญชี',
    accountAddress: 'ที่อยู่กระเป๋า/เลขบัญชี',
    historyDeposit: 'ประวัติการเติมเงิน',
    historyWithdraw: 'ประวัติการถอนเงิน',
    tradeHistory: 'ประวัติการซื้อ-ขาย (Trade History)',
    noTradeHistory: 'ไม่มีประวัติการซื้อขาย',
    actionBuy: 'ซื้อ (Buy)',
    actionSell: 'ขาย (Sell)',
    crypto: 'คริปโทฯ (Crypto)',
    commodity: 'สินค้าโภคภัณฑ์ (Commodity)',
    stock: 'หุ้น (Stock)',
    allCategories: 'ทุกหมวดหมู่ (All)',
    activityLedger: 'สมุดบัญชีธุรกรรม',
    all: 'ทั้งหมด',
    trades: 'การเทรด',
    wallets: 'รายการบัญชี',
    allAssets: 'สินทรัพย์ทั้งหมด',
    noRecordsFound: 'ไม่พบข้อมูลธุรกรรม',
    trackActivityDesc: 'ติดตามการเทรด, เงินฝาก และการโอนเงินของคุณได้ที่นี่',
    transactionId: 'รหัสธุรกรรม',
    executionPrice: 'ราคาที่ทำรายการ',
    quantity: 'จำนวน',
    type: 'ประเภท',
    noActivityInCat: 'ไม่มีรายการธุรกรรมในหมวดหมู่นี้',
    active: 'ACTIVE',
    investmentAndTime: 'เงินลงทุน และ เวลา',
    profitIfWon: 'กำไรที่ได้รับ',
    predictUp: 'ทายขึ้น',
    predictDown: 'ทายลง',
    placingTrade: 'กำลังเปิดออเดอร์',
    activeBinaryTrades: 'ออเดอร์ที่กำลังจับเวลา',
    setupOption: 'ตั้งค่าคำสั่งซื้อ',
    confirmTradeSetup: 'ยืนยันคำสั่งซื้อ',
    congratulations: 'ขอแสดงความยินดี!',
    predictionCorrect: 'การทายผล',
    wasCorrect: 'ของคุณถูกต้อง',
    totalPayout: 'เงินรางวัลสุทธิ',
    collectProfit: 'รับเงินเข้ากระเป๋า',
    searchAssets: 'ค้นหาตลาด',
    marketOverview: 'ภาพรวมตลาด',
    bullish: 'ตลาดขาขึ้น',
    bearish: 'ตลาดขาลง',
    tradeNow: 'เริ่มเทรด',
    upCall: 'ขึ้น (Call)',
    downPut: 'ลง (Put)',
    assetInfo: 'ข้อมูลสินทรัพย์',
    livePrice: 'ราคาล่าสุด',
    viewAll: 'ดูทั้งหมด',
    availableBalance: 'ยอดเงินคงเหลือ',
    minimum: 'ขั้นต่ำ',
    minTradeAmountError: 'จำนวนเงินลงทุนขั้นต่ำคือ ',
    win: 'ชนะ',
    loss: 'แพ้',
    marketsActive: 'ตลาดที่เปิดอยู่',
    topGainer: 'บวกสูงสุด',
    globalVol: 'ปริมาณรวม',
    marketStatus: 'สภาวะตลาด',
    latestGoldPrice: 'ราคาทองคำล่าสุด (XAU/USD)',
    goldHeroDesc: 'ราคาทองคำยังคงแข็งแกร่ง เนื่องจากความผันผวนของตลาดทำให้มีความต้องการสินทรัพย์ปลอดภัยเพิ่มขึ้น เทรด GOLD โดยไม่มีค่าธรรมเนียม',
    recommendedAssets: 'สินทรัพย์แนะนำ',
    smartAiSelection: 'การคัดเลือกอัจฉริยะ',
    marketInsights: 'บทวิเคราะห์ตลาด',
    justNow: 'เมื่อครู่',
    insightTitle1: 'ตลาดคริปโทฯ เริ่มส่งสัญญาณฟื้นตัวหลังการเปิดเผยข้อมูลการประชุม FOMC',
    insightDesc1: 'นักวิเคราะห์คาดการณ์ว่าตลาดจะเป็นขาขึ้นต่อ (Bullish) สำหรับสินทรัพย์หลักอย่าง BTC และ ETH ในอีก 48 ชั่วโมงข้างหน้า',
    insightNews1: 'แรงขุด Bitcoin ทำสถิติสูงสุดใหม่ (ATH)',
    insightNews2: 'ดัชนีดอลลาร์สหรัฐ (DXY) เริ่มมีการย่อตัวเล็กน้อย',
    howItWorks: 'ขั้นตอนการใช้งาน MetaBridge',
    howItWorksDesc: 'เริ่มต้นเส้นทางการเทรดของคุณด้วยแพลตฟอร์มที่ง่าย มั่นคง และรวดเร็ว ใน 3 ขั้นตอน',
    step1Title: 'ฝากเงินเข้ากระเป๋า',
    step1Desc: 'ฝากเงินโดยใช้ช่องทางชำระเงินที่ปลอดภัยและรองรับธนาคารไทย',
    step2Title: 'เลือกสินทรัพย์',
    step2Desc: 'เลือกเทรดได้มากกว่า 100 ตลาด ทั้งคริปโทฯ หุ้น และสินค้าโภคภัณฑ์',
    step3Title: 'เริ่มทำกำไร',
    step3Desc: 'ส่งคำสั่งซื้อขายด้วยระบบที่รวดเร็วและแม่นยำระดับสถาบัน',
    notifications: 'การแจ้งเตือน',
    systemNotifications: 'แจ้งเตือนระบบ (Push)',
    enableNotifications: 'เปิดการแจ้งเตือน',
    notificationsEnabled: 'เปิดแจ้งเตือนแล้ว',
    notificationsDisabled: 'ปิดแจ้งเตือน',
    notificationsDenied: 'การแจ้งเตือนถูกปฏิเสธ (โปรดตรวจสอบการตั้งค่าบราวเซอร์)',
    notificationsUnsupported: 'บราวเซอร์ของคุณไม่รองรับการแจ้งเตือน',
    wonNotificationTitle: '🚀 ยินดีด้วย! คุณชนะแล้ว!',
    shareApp: 'แชร์แอพ',
    createShortcut: 'สร้างทางลัดหน้าจอ',
    installApp: 'ติดตั้งแอพ',
    linkCopied: 'คัดลอกลิงก์แล้ว!',
    installInstructions: 'ติดตั้ง MetaBridge บน iPhone ของคุณ',
    step1: 'ขั้นตอนที่ 1',
    safariShare: 'กดปุ่ม Share ในเบราว์เซอร์ Safari',
    step2: 'ขั้นตอนที่ 2',
    safariAddHome: 'เลื่อนลงมาแล้วเลือก "Add to Home Screen"',
    launchFromHome: 'เข้าใช้งานจากหน้าจอโฮมเพื่อประสบการณ์ที่ดีที่สุด',
    iUnderstand: 'รับทราบ',
    languageSettings: 'ตั้งค่าภาษา',
    shareAndInstall: 'แชร์และติดตั้ง',
    recommended: 'แนะนำ',
    copyLink: 'คัดลอกลิงก์',
    socialShare: 'แชร์โซเชียล',
    appExperience: 'ประสบการณ์ใช้งานแอพที่ดีที่สุด',
    back: 'กลับ',
    close: 'ปิด',
    copiedLabel: 'คัดลอกแล้ว!',
    copyLabel: 'คัดลอก',
    selectDepositMethod: 'เลือกสกุลเงินที่ต้องการฝาก',
    selectWithdrawMethod: 'เลือกสกุลเงินที่ต้องการถอน',
    amountToDeposit: 'จำนวนที่โอน',
    amountToWithdraw: 'จำนวนเงิน',
    notifyDeposit: 'แจ้งโอนเงิน',
    submittingDeposit: 'กำลังส่งคำขอ...',
    depositErrorTitle: 'ไม่สามารถยืนยันการโอนได้',
    depositErrorDesc: 'ระบบไม่สามารถตรวจสอบการโอนเงินของคุณได้อัตโนมัติ กรุณาติดต่อทีมสนับสนุนเพื่อยืนยันและเติมยอดเข้าบัญชี',
    confirmWithdrawal: 'ยืนยันการถอนเงิน',
    processingWithdrawal: 'กำลังดำเนินการ...',
    withdrawProblemTitle: 'พบปัญหาในการถอนเงิน',
    withdrawProblemDesc: 'ระบบไม่สามารถดำเนินการถอนเงินได้โดยอัตโนมัติ กรุณาติดต่อทีมสนับสนุนเพื่อดำเนินการต่อ',
    bankName: 'ธนาคาร',
    accountNumberLabel: 'เลขบัญชี',
    swiftNetwork: 'SWIFT/เครือข่าย',
    checkDetailsWarning: '⚠️ กรุณาตรวจสอบข้อมูลบัญชีให้ถูกต้องก่อนยืนยัน',
    contactSupport: 'ติดต่อฝ่ายสนับสนุน',
    availableBalanceLabel: 'ยอดคงเหลือ',
    amount: 'จำนวน',
    currency: 'สกุลเงิน',
    walletAddress: 'ที่อยู่กระเป๋า',
    predictionAmount: 'เงินเดิมพัน (ทายผล)',
    predictionStarted: 'เริ่มการทายผลสำเร็จ',
    bet: 'เดิมพัน',
    transactionsUpTo: 'รายการย้อนหลังจนถึง',
    dateTime: 'วันและเวลา',
    today: 'วันนี้',
    matched: 'จับคู่แล้ว',
    success: 'สำเร็จ',
    pending: 'รอดำเนินการ',
    viewMarketDetails: 'ดูรายละเอียดตลาด',
    forgotPassword: 'ลืมรหัสผ่าน?',
    resetPassword: 'กู้คืนรหัสผ่าน',
    verificationCode: 'รหัสยืนยัน',
    enterCodeSentTo: 'กรอกรหัส 6 หลักที่เราส่งไปที่',
    resendCode: 'ส่งรหัสอีกครั้ง',
    invalidOtp: 'รหัสยืนยันไม่ถูกต้องหรือหมดอายุ',
    passwordChanged: 'เปลี่ยนรหัสผ่านสำเร็จ!',
    checkEmailForCode: 'โปรดตรวจสอบอีเมลของคุณเพื่อรับรหัสยืนยัน',
    newPassword: 'รหัสผ่านใหม่',
    confirmNewPassword: 'ยืนยันรหัสผ่านใหม่',
    accountSecurity: 'บัญชีและความปลอดภัย',
    loginMethods: 'ช่องทางการเข้าสู่ระบบ',
    connected: 'เชื่อมต่อแล้ว',
    changeEmail: 'เปลี่ยนอีเมล',
    newEmail: 'อีเมลใหม่',
    updateEmail: 'อัปเดตอีเมล',
    emailUpdated: 'เปลี่ยนอีเมลสำเร็จ!',
    managePersonalInfo: 'จัดการข้อมูลส่วนตัวและสถานะ KYC ของคุณ',
    discard: 'ยกเลิก',
    bankDescription: 'รายละเอียดปลายทางสำหรับการถอนเงินของคุณ',
    bankWarning: 'โปรดตรวจสอบให้แน่ใจว่าข้อมูลทั้งหมดถูกต้อง ข้อมูลที่ไม่ถูกต้องอาจทำให้สูญเสียเงินทุนอย่างถาวรในระหว่างการถอน',
    securityDescription: 'จัดการบัญชีที่เชื่อมต่อและการตั้งค่าความปลอดภัยของคุณ',
    emailLogin: 'เข้าสู่ระบบด้วยอีเมล',
    loginHistory: 'ประวัติการเข้าสู่ระบบ',
    recentActivity: 'กิจกรรมล่าสุด',
    viewRecentSignins: 'ดูการลงชื่อเข้าใช้ล่าสุดในบัญชีของคุณ',
    viewHistory: 'ดูประวัติ',
    accountPassword: 'รหัสผ่านบัญชี',
    updatePasswordDesc: 'อัปเดตรหัสผ่านของคุณเป็นประจำเพื่อความปลอดภัย',
    ensureStrongPassword: 'ตรวจสอบให้แน่ใจว่าบัญชีของคุณใช้รหัสผ่านที่รัดกุมและไม่ซ้ำกัน',
    loginHistoryDesc: 'การลงชื่อเข้าใช้ล่าสุดในบัญชีของคุณจากอุปกรณ์ต่างๆ',
    lastSignedIn: 'ใช้งานล่าสุด',
    noRecentActivity: 'ไม่พบกิจกรรมล่าสุด',
    administrator: 'ผู้ดูแลระบบ',
    traderAccount: 'บัญชีเทรดเดอร์',
    navigation: 'เมนูนำทาง',
    appTools: 'เครื่องมือเสริม',
    adminDashboard: 'เครื่องมือผู้ดูแลระบบ',
    signingOut: 'กำลังออกจากระบบ...',
    logout: 'ออกจากระบบ',
    txCodeLabel: 'รหัสอ้างอิง / สลิปโอน',
    txCodePlaceholder: 'วางรหัสสลิปหรือรหัสอ้างอิงที่นี่',
    paste: 'วาง',
    pasted: 'วางแล้ว!',
    underDevelopment: 'อยู่ระหว่างพัฒนา — ระบบตรวจสอบอัตโนมัติ',
    verifyCurrentEmail: 'ยืนยันอีเมลปัจจุบัน',
    verifyCurrentEmailDesc: 'เพื่อความปลอดภัย เราจำเป็นต้องยืนยันอีเมลปัจจุบันของคุณ:',
    sendCode: 'ส่งรหัสยืนยัน',
    enterVerificationCode: 'กรอกรหัสยืนยัน',
    checkInboxCode: 'โปรดตรวจสอบกล่องจดหมายของคุณสำหรับรหัส 6 หลักที่เราส่งไปยังอีเมล',
    verifyCode: 'ยืนยันรหัส',
    didntGetCode: 'ไม่ได้รับรหัสใช่ไหม? ส่งอีกครั้ง',
    enterNewEmailDesc: 'โปรดป้อนที่อยู่อีเมลใหม่ของคุณ เราจะส่งรหัสยืนยันเพื่อยืนยัน',
    verifyNewEmail: 'ยืนยันอีเมลใหม่',
    checkInboxNewEmail: 'โปรดตรวจสอบกล่องจดหมายสำหรับรหัส 6 หลักที่เราส่งไปยัง',
    verifyAndUpdateEmail: 'ยืนยันและอัปเดตอีเมล',
    requestPasswordReset: 'ขอรีเซ็ตรหัสผ่าน',
    sendCodeToEmail: 'เราจะส่งรหัสยืนยัน 6 หลักไปที่อีเมลที่ลงทะเบียน:',
    setNewPassword: 'ตั้งรหัสผ่านใหม่',
    codeVerifiedNewPassword: 'รหัสของคุณได้รับการยืนยันแล้ว โปรดป้อนรหัสผ่านใหม่ของคุณด้านล่าง',
    currentPasswordLabel: 'รหัสผ่านปัจจุบัน',
    newPasswordLabel: 'รหัสผ่านใหม่',
    confirmNewPasswordLabel: 'ยืนยันรหัสผ่านใหม่',
    verifyCodeLabel: 'รหัสยืนยัน',
    updatePasswordDesc2: 'ป้อนรหัสผ่านปัจจุบันและรหัสผ่านใหม่ของคุณ',
    historyDepositDesc: 'ดูรายการฝากเงินล่าสุดของคุณ',
    noDepositHistory: 'ไม่พบประวัติการฝากเงิน',
    systemNotificationsDesc: 'รับการแจ้งเตือนผลการเทรดของคุณทันที แม้ว่าคุณจะไม่ได้ใช้งานแอปพลิเคชัน',
    notificationTypes: 'ประเภทการแจ้งเตือน',
    tradeOutcomes: 'ผลการเทรด (ชนะ/แพ้)',
    priceAlerts: 'แจ้งเตือนราคา',
    languageSettingsDesc: 'เลือกภาษาที่คุณต้องการแสดงบนแพลตฟอร์ม',
    translationsApplied: 'การแปลภาษาจะถูกปรับใช้ทันทีทั่วทั้งแอปพลิเคชัน ข้อมูลตลาดหรือข่าวสารบางส่วนอาจยังคงอยู่ในภาษาต้นฉบับ',
    otpPlaceholder: 'รหัส OTP',
  },
  en: {
    home: 'Home',
    news: 'News',
    trade: 'Trade',
    history: 'History',
    wallet: 'Wallet',
    settings: 'Settings',
    gold: 'Gold',
    latestPrice: 'Latest Price',
    change24h: '24h Change',
    buy: 'Buy',
    sell: 'Sell',
    deposit: 'Deposit',
    staking: 'Staking',
    withdraw: 'Withdraw',
    myStaking: 'My Staking',
    recentTransactions: 'Recent Transactions',
    totalBalance: 'Total Balance',
    verification: 'Identity Verification',
    bankDetails: 'Bank Details',
    changePassword: 'Change Password',
    login: 'Login',
    register: 'Register',
    username: 'Username',
    password: 'Password',
    email: 'Email',
    phone: 'Phone Number',
    confirmPassword: 'Confirm Password',
    save: 'Save',
    firstName: 'First Name',
    lastName: 'Last Name',
    address: 'Address',
    network: 'Network',
    accountName: 'Account Name',
    accountAddress: 'Account Address',
    historyDeposit: 'Deposit History',
    historyWithdraw: 'Withdraw History',
    tradeHistory: 'Trade History',
    noTradeHistory: 'No trade history available.',
    actionBuy: 'Buy',
    actionSell: 'Sell',
    crypto: 'Crypto',
    commodity: 'Commodity',
    stock: 'Stock',
    allCategories: 'All Categories',
    activityLedger: 'Activity Ledger',
    all: 'All',
    trades: 'Trades',
    wallets: 'Wallets',
    allAssets: 'All Assets',
    noRecordsFound: 'No records found',
    trackActivityDesc: 'Track your trades, deposits, and transfers in one place',
    transactionId: 'Transaction ID',
    executionPrice: 'Execution Price',
    quantity: 'Quantity',
    type: 'Type',
    noActivityInCat: 'There is no activity in this category yet.',
    active: 'ACTIVE',
    investmentAndTime: 'Investment & Time',
    profitIfWon: 'Profit if Won',
    predictUp: 'Predict Up',
    predictDown: 'Predict Down',
    placingTrade: 'Placing trade',
    activeBinaryTrades: 'Active Binary Trades',
    setupOption: 'Setup Option',
    confirmTradeSetup: 'Confirm Trade Setup',
    congratulations: 'Congratulations!',
    predictionCorrect: 'Your prediction for',
    wasCorrect: 'was correct.',
    totalPayout: 'Total Payout',
    collectProfit: 'Collect Profit',
    searchAssets: 'Search Assets',
    marketOverview: 'Market Overview',
    bullish: 'Bullish',
    bearish: 'Bearish',
    tradeNow: 'Trade Now',
    upCall: 'Up (Call)',
    downPut: 'Down (Put)',
    assetInfo: 'Asset Information',
    livePrice: 'Live Price',
    viewAll: 'View All',
    availableBalance: 'Available Balance',
    minimum: 'Minimum',
    minTradeAmountError: 'Minimum trade amount is ',
    win: 'WIN',
    loss: 'LOSS',
    marketsActive: 'Markets Active',
    topGainer: 'Top Gainer',
    globalVol: 'Global Vol',
    marketStatus: 'Market Status',
    latestGoldPrice: 'LATEST XAU/USD PRICE',
    goldHeroDesc: 'Gold prices remain robust as market volatility drives demand for safe-haven assets. Trade GOLD with 0% commissions.',
    recommendedAssets: 'Recommended Assets',
    smartAiSelection: 'Smart AI Selection',
    marketInsights: 'Market Insights',
    justNow: 'Just Now',
    insightTitle1: 'Crypto markets showing strong recovery signs after FOMC meeting details.',
    insightDesc1: 'Analysts suggest a Bullish continuation for major assets like BTC and ETH in the coming 48 hours.',
    insightNews1: 'Bitcoin hash rate hits new ATH high.',
    insightNews2: 'US Dollar index shows slight correction.',
    howItWorks: 'How MetaBridge Works',
    howItWorksDesc: 'Start your trading journey with our simple, secure, and fast platform in three easy steps.',
    step1Title: 'Fund Wallet',
    step1Desc: 'Deposit funds using our secure localized payment gateways.',
    step2Title: 'Select Asset',
    step2Desc: 'Browse through 100+ Crypto, Stock and Commodity markets.',
    step3Title: 'Execute Trade',
    step3Desc: 'Place your order with institutional-grade low latency.',
    notifications: 'Notifications',
    systemNotifications: 'System Notifications (Push)',
    enableNotifications: 'Enable Notifications',
    notificationsEnabled: 'Notifications Enabled',
    notificationsDisabled: 'Notifications Disabled',
    notificationsDenied: 'Notifications Denied (Please check browser settings)',
    notificationsUnsupported: 'Browser does not support notifications',
    wonNotificationTitle: '🚀 Congratulations! You Won!',
    shareApp: 'Share App',
    createShortcut: 'Create Shortcut',
    installApp: 'Install App',
    linkCopied: 'Link Copied!',
    installInstructions: 'Install MetaBridge on your iPhone',
    step1: 'Step 1',
    safariShare: 'Tap the Share button in Safari',
    step2: 'Step 2',
    safariAddHome: 'Scroll down and select "Add to Home Screen"',
    launchFromHome: 'Launch from your home screen for the full app experience.',
    iUnderstand: 'I Understand',
    languageSettings: 'Language Settings',
    shareAndInstall: 'Share & Install',
    recommended: 'RECOMMENDED',
    copyLink: 'Copy Link',
    socialShare: 'Social Share',
    appExperience: 'Best App Experience',
    back: 'Back',
    close: 'Close',
    copiedLabel: 'Copied!',
    copyLabel: 'Copy',
    selectDepositMethod: 'Select Deposit Method',
    selectWithdrawMethod: 'Select Withdrawal Method',
    amountToDeposit: 'Amount to Deposit',
    amountToWithdraw: 'Withdrawal Amount',
    notifyDeposit: 'Confirm Transfer',
    submittingDeposit: 'Submitting Request...',
    depositErrorTitle: 'Verification Failed',
    depositErrorDesc: 'The system could not verify your transfer automatically. Please contact support to credit your account.',
    confirmWithdrawal: 'Confirm Withdrawal',
    processingWithdrawal: 'Processing...',
    withdrawProblemTitle: 'Withdrawal Issue',
    withdrawProblemDesc: 'System cannot process your withdrawal automatically. Please contact support to proceed.',
    bankName: 'Bank Name',
    accountNumberLabel: 'Account Number',
    swiftNetwork: 'SWIFT/Network',
    checkDetailsWarning: '⚠️ Please verify account details before confirming',
    contactSupport: 'Contact Support',
    availableBalanceLabel: 'Balance',
    amount: 'Amount',
    currency: 'Currency',
    walletAddress: 'Wallet Address',
    predictionAmount: 'Prediction Amount',
    predictionStarted: 'Prediction Started Successfully',
    bet: 'Bet',
    transactionsUpTo: 'Transactions up to',
    dateTime: 'Date & Time',
    today: 'Today',
    matched: 'Matched',
    success: 'Success',
    pending: 'Pending',
    viewMarketDetails: 'View Market Details',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    verificationCode: 'Verification Code',
    enterCodeSentTo: 'Enter the 6-digit code we sent to',
    resendCode: 'Resend Code',
    invalidOtp: 'Invalid or expired verification code',
    passwordChanged: 'Password changed successfully!',
    checkEmailForCode: 'Please check your email for the verification code',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    accountSecurity: 'Account & Security',
    loginMethods: 'Login Methods',
    connected: 'Connected',
    changeEmail: 'Change Email',
    newEmail: 'New Email',
    updateEmail: 'Update Email',
    emailUpdated: 'Email updated successfully!',
    managePersonalInfo: 'Manage your personal information and KYC status',
    discard: 'Discard',
    bankDescription: 'Your withdrawal destination details',
    bankWarning: 'Please ensure all details are correct. Incorrect information may lead to permanent loss of funds during withdrawal.',
    securityDescription: 'Manage your connected accounts and security settings',
    emailLogin: 'Email Login',
    loginHistory: 'Login History',
    recentActivity: 'Recent Activity',
    viewRecentSignins: 'View recent sign-ins on your account',
    viewHistory: 'View History',
    accountPassword: 'Account Password',
    updatePasswordDesc: 'Regularly update your password to stay secure',
    ensureStrongPassword: 'Ensure your account is using a strong, unique password',
    loginHistoryDesc: 'Recent sign-ins on your account across devices.',
    lastSignedIn: 'LAST SIGNED IN',
    noRecentActivity: 'No recent activity found.',
    administrator: 'Administrator',
    traderAccount: 'Trader Account',
    navigation: 'NAVIGATION',
    appTools: 'App Tools',
    adminDashboard: 'Admin Dashboard',
    signingOut: 'Signing out...',
    logout: 'Logout',
    txCodeLabel: 'Transaction / Slip Code',
    txCodePlaceholder: 'Paste your slip or reference code here',
    paste: 'Paste',
    pasted: 'Pasted!',
    underDevelopment: 'Under Development — Auto-verification system',
    verifyCurrentEmail: 'Verify Current Email',
    verifyCurrentEmailDesc: 'For your security, we need to verify your current email:',
    sendCode: 'Send Code',
    enterVerificationCode: 'Enter Verification Code',
    checkInboxCode: 'Check your inbox for the 6-digit code we sent to your current email.',
    verifyCode: 'Verify Code',
    didntGetCode: "Didn't get code? Resend",
    enterNewEmailDesc: 'Please enter your new email address. We will send a verification code to confirm it.',
    verifyNewEmail: 'Verify New Email',
    checkInboxNewEmail: 'Check your inbox for the 6-digit code we sent to',
    verifyAndUpdateEmail: 'Verify & Update Email',
    requestPasswordReset: 'Request Password Reset',
    sendCodeToEmail: 'We will send a 6-digit verification code to your registered email:',
    setNewPassword: 'Set New Password',
    codeVerifiedNewPassword: 'Your code is verified. Please enter your new password below.',
    currentPasswordLabel: 'Current Password',
    newPasswordLabel: 'New Password',
    confirmNewPasswordLabel: 'Confirm New Password',
    verifyCodeLabel: 'Verification Code',
    updatePasswordDesc2: 'Enter your current and new password below.',
    historyDepositDesc: 'View your recent deposit transactions',
    noDepositHistory: 'No deposit history found',
    systemNotificationsDesc: 'Get instant alerts for your trading results even when you are not looking at the app.',
    notificationTypes: 'Notification Types',
    tradeOutcomes: 'Trade Outcomes (Win/Loss)',
    priceAlerts: 'Price Alerts',
    languageSettingsDesc: 'Select your preferred display language for the platform.',
    translationsApplied: 'Translations are applied instantly across the entire application interface. Some market data or news content may remain in its original language.',
    otpPlaceholder: 'OTP Code',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('appLanguage');
    return (saved === 'th' || saved === 'en') ? saved as Language : 'th';
  });

  useEffect(() => {
    localStorage.setItem('appLanguage', language);
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
